### ISSUE TITLE
type error on running on ubuntu 14.04

### ISSUE THREAD

**Issue by microlaser** [DanNixon/PlayMusicCL#24]
I tried running this on ubuntu 14.04 and got the following type error:

Traceback (most recent call last):
  File "/usr/local/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.1', 'console_scripts', 'playmusiccl')()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/__init__.py", line 7, in run
    main()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/playmusiccl.py", line 735, in main
    __MusicClient__ = GPMClient(config.get("google_user"), config.get("google_pass"), config.get("google_deviceid"))
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/playmusiccl.py", line 50, in __init__
    self.logged_in = self.__api.login(email, password)
TypeError: login() takes exactly 4 arguments (3 given)

The install worked fine with one hitch, it seems my version of ubuntu ships with an old version of python six.  I overcame this problem by manually installing the next release candidate for this package:

sudo dpkg -i python-six_1.7.3-2_all.deb

**Comment by DanNixon** [comment]
Can you try this again. I think this issue may have been fixed along with another in the last changes I made.
