### ISSUE TITLE
KeyError 

### ISSUE THREAD

**Issue by romusters** [DanNixon/PlayMusicCL#25]
```
Creating GStreamer player...
Updating local library from Google Play Music...
Traceback (most recent call last):
  File "/usr/local/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.1', 'console_scripts', 'playmusiccl')()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/__init__.py", line 7, in run
    main()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/playmusiccl.py", line 746, in main
    __MusicClient__.update_local_lib()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/playmusiccl.py", line 109, in update_local_lib
    song = song_map[track["trackId"]]
KeyError: u'Td7ukufwrvbjchpkyg6g3vawtae'
```

**Comment by DanNixon** [comment]
Probably related to #21.

**Comment by DanNixon** [comment]
Can you give this another try, I have a feeling this would have been fixed in a recent PR.
