### ISSUE TITLE
TypeError: login() takes exactly 3 arguments (4 given)

### ISSUE THREAD

**Issue by lpar** [DanNixon/PlayMusicCL#27]
Reinstalled from current HEAD via `python setup.py install`:

```
% playmusiccl
Logging in to Google Play Music...
Traceback (most recent call last):
  File "/usr/local/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.1', 'console_scripts', 'playmusiccl')()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/__init__.py", line 7, in run
    main()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/playmusiccl.py", line 858, in main
    config.get("google_deviceid"))
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.1-py2.7.egg/playmusiccl/playmusiccl.py", line 61, in __init__
    self.logged_in = self.__api.login(email, password, device_id)
TypeError: login() takes exactly 3 arguments (4 given)
```

Config is the same as when I previously installed via pip, which got past this point.

**Comment by DanNixon** [comment]
Can you try running `python setup --update gmusicapi`.

**Comment by lpar** [comment]
It didn't seem to understand any kind of update command or option. But I removed gmusicapi* from /usr/local/lib/python, ran setup.py install again, and now I get further. Thanks.

**Comment by DanNixon** [comment]
My mistake, the flag is actually `--upgrade`.

**Comment by lpar** [comment]
And unfortunately it's not mentioned in the setup.py help for the install command, which I did check, or in the top level help.

**Comment by lpar** [comment]
Looks as if `gstreamer0.10-plugins-ugly` is the magic package that fixes it for me, though I also installed the lame, alsa and pulseaudio packages.
