### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by nspboarderdude** [DanNixon/PlayMusicCL#33]
Sorry for the vague title. I'm not sure what this means. 

Logging in to Google Play Music...
Creating GStreamer player...
Updating local library from Google Play Music...
Traceback (most recent call last):
  File "/usr/local/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.2', 'console_scripts', 'playmusiccl')()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/__init__.py", line 8, in run
    main()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/playmusiccl.py", line 870, in main
    __MusicClient__.update_local_lib()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/playmusiccl.py", line 86, in update_local_lib
    song_artist = song["artist"]
KeyError: 'artist'

I'm using Python 2.7.6.

**Comment by buzzbo** [comment]
Not sure if this is related.

    /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
    /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
    /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
    ESC]2;Google Play Music^GLogging in to Google Play Music...
    Creating GStreamer player...
    Updating local library from Google Play Music...
    Traceback (most recent call last):
      File "/usr/local/bin/playmusiccl", line 9, in <module>
        load_entry_point('playmusiccl==0.6.1', 'console_scripts', 'playmusiccl')()
      File "/usr/local/lib/python2.7/dist-packages/playmusiccl/__init__.py", line 7, in run
        main()
      File "/usr/local/lib/python2.7/dist-packages/playmusiccl/playmusiccl.py", line 745, in main
        __MusicClient__.update_local_lib()
      File "/usr/local/lib/python2.7/dist-packages/playmusiccl/playmusiccl.py", line 61, in update_local_lib
        songs = self.__api.get_all_songs()
      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 107, in get_all_songs
        tracks = self._get_all_items(mobileclient.ListTracks, incremental, include_deleted)
      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 897, in _get_all_items
        return [s for chunk in generator for s in chunk]
      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 910, in _get_all_items_incremental
        **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
        return protocol.perform(self.session, self.validate, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
        response = session.send(req_kwargs, cls.required_auth)
      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 81, in send
        raise NotLoggedIn
    gmusicapi.exceptions.NotLoggedIn

**Comment by CColon1** [comment]
I am also receiving the NotLoggedIn exception, has anyone found a work around for this?
