### ISSUE TITLE
Assertion or type error

### ISSUE THREAD

**Issue by brownsnake** [DanNixon/PlayMusicCL#38]
If I install by cloning the latest GitHub master branch, I get an Assertion error. If I install with pip, I get the type error about login() taking 4 arguments but only getting three.

**Comment by motevets** [comment]
I am also seeing this.  Here is the output:

```
$ playmusiccl
Logging in to Google Play Music...
Traceback (most recent call last):
  File "/usr/local/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.1', 'console_scripts', 'playmusiccl')()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl/__init__.py", line 7, in run
    main()
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl/playmusiccl.py", line 735, in main
    __MusicClient__ = GPMClient(config.get("google_user"), config.get("google_pass"), config.get("google_deviceid"))
  File "/usr/local/lib/python2.7/dist-packages/playmusiccl/playmusiccl.py", line 50, in __init__
    self.logged_in = self.__api.login(email, password)
TypeError: login() takes exactly 4 arguments (3 given)
```

**Comment by motevets** [comment]
I fixed it by installing the latest version using:
```bash
git clone https://github.com/DanNixon/PlayMusicCL.git
cd PlayMusicCL
sudo python setup.py install
```

It looks like the issue may have been fixed between 0.6.1 (which is on Pypi) and 0.6.2 (which is was `master` on Github is).  @DanNixon should Pypi be updated?
