### ISSUE TITLE
GetDeviceID.py cannot determine device type.

### ISSUE THREAD

**Issue by charlescbeebe** [DanNixon/PlayMusicCL#42]
```
$ python GetDeviceID.py
Username: ...
Password: ...
<string>:2: GmusicapiWarning: get_registered_devices is deprecated and may break unexpectedly.
prefer Mobileclient.get_registered_devices
Traceback (most recent call last):
  File "GetDeviceID.py", line 22, in <module>
    if device['type'] == 'PHONE':
KeyError: 'type'
```

**Comment by mtelesha** [comment]
Traceback (most recent call last):
  File "GetDeviceID.py", line 18, in <module>
    api.login(user, passwd)
  File "/usr/lib/python2.7/site-packages/gmusicapi-10.0.1-py2.7.egg/gmusicapi/clients/webclient.py", line 60, in login
    if not self.session.login(email, password):
  File "/usr/lib/python2.7/site-packages/gmusicapi-10.0.1-py2.7.egg/gmusicapi/session.py", line 110, in login
    'continue': 'https://play.google.com/music/listen'})
  File "build/bdist.linux-x86_64/egg/mechanicalsoup/browser.py", line 32, in get
  File "build/bdist.linux-x86_64/egg/mechanicalsoup/browser.py", line 23, in add_soup
TypeError: __init__() got multiple values for keyword argument 'features'
