### ISSUE TITLE
Does the Libre.fm hosts file hack work with this?

### ISSUE THREAD

**Issue by bulletfreak** [DanNixon/PlayMusicCL#47]
I'm thinking of going back to Linux here in a few days or so and I was wondering if I called scrobble to Libre.fm via the built in Last.fm plugin.

**Comment by DanNixon** [comment]
The [PyLast](https://github.com/pylast/pylast) docs say it is compatible with Libre.fm so I can't see any reason why not (at least without too much modification).

You'd have to generate your own API keys and replace the existing ones.

**Comment by bulletfreak** [comment]
Here's what i got with the hosts file hack
`[bulletfreak@Frostmourne ~]$ playmusiccl
Logging in to Google Play Music...
Logging in to Last.fm...
Traceback (most recent call last):
  File "/usr/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.2', 'console_scripts', 'playmusiccl')()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/__init__.py", line 8, in run
    main()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/playmusiccl.py", line 864, in main
    ("lastfm_user" in config))
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/playmusiccl.py", line 313, in __init__
    password_hash=password_hash)
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 853, in __init__
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 194, in __init__
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1258, in get_session_key
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1137, in execute
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1128, in _download_response
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1157, in _check_response_for_errors
pylast.WSError: Authentication Failed - You do not have permissions to access the service
[bulletfreak@Frostmourne ~]$ sudo playmusiccl
[sudo] password for bulletfreak: 
Can't find ~/.playmusicclrc
[bulletfreak@Frostmourne ~]$ playmusiccl     
Logging in to Google Play Music...
Logging in to Last.fm...
Traceback (most recent call last):
  File "/usr/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.2', 'console_scripts', 'playmusiccl')()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/__init__.py", line 8, in run
    main()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/playmusiccl.py", line 864, in main
    ("lastfm_user" in config))
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.2-py2.7.egg/playmusiccl/playmusiccl.py", line 313, in __init__
    password_hash=password_hash)
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 853, in __init__
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 194, in __init__
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1258, in get_session_key
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1137, in execute
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1128, in _download_response
  File "build/bdist.linux-x86_64/egg/pylast/__init__.py", line 1157, in _check_response_for_errors
pylast.WSError: Authentication Failed - You do not have permissions to access the service`

What do you mean generate my own API keys?
