### ISSUE TITLE
GetDeviceID throw import error

### ISSUE THREAD

**Issue by holla2040** [DanNixon/PlayMusicCL#52]
holla@hendrix[547]: py GetDeviceID.py 
Traceback (most recent call last):
  File "GetDeviceID.py", line 9, in <module>
    import gmusicapi
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.0.1-py2.7.egg/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.0.1-py2.7.egg/gmusicapi/clients/__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.0.1-py2.7.egg/gmusicapi/clients/webclient.py", line 11, in <module>
    from gmusicapi.protocol import webclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.0.1-py2.7.egg/gmusicapi/protocol/webclient.py", line 6, in <module>
    from six import raise_from
ImportError: cannot import name raise_from

I've installed  six-1.10.0

**Comment by markmark1** [comment]
ImportError: cannot import name raise_from
